databases:
  - ESmanager_DB: Renderで作成したDBアプリ名
    esmanager_db: 「Info内のConnectionsにあるDatabase」を入れる
    ESmanager: Renderで作成したRailsのアプリ名
    region: singapore

services:
  - type: web
    ESmanager: Renderで作成したRailsのアプリ名
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          ESmanager_DB: Renderで作成したDBアプリ名
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false